### ISSUE TITLE
Excessive JOOQ exception messages

### ISSUE THREAD

**Issue by FrankChen021** [FrankChen021/bithon#193]
Try to suppress these messages

```bash
2021-10-07 21:03:52.624 ERROR 3960 --- [ception-metrics] o.s.b.a.jooq.JooqExceptionTranslator     : [bTxId:, bSpanId:] Execution of SQL statement failed.

org.springframework.dao.DuplicateKeyException: jOOQ; SQL [insert into "bithon_exception_metrics" ("timestamp", "appName", "instanceName", "uri", "className", "exceptionCount") values (timestamp '2021-10-07 21:03:52.614', 'bithon-server-test', '10.169.24.104:9897', '', '', 1)]; Unique index or primary key violation: "PUBLIC.idx_bithon_exception_metrics_dimensions_INDEX_7 ON PUBLIC.bithon_exception_metrics(timestamp, appName, instanceName, uri, className) VALUES 438"; SQL statement:
insert into "bithon_exception_metrics" ("timestamp", "appName", "instanceName", "uri", "className", "exceptionCount") values (timestamp '2021-10-07 21:03:52.614', 'bithon-server-test', '10.169.24.104:9897', '', '', 3) [23505-200]; nested exception is org.h2.jdbc.JdbcSQLIntegrityConstraintViolationException: Unique index or primary key violation: "PUBLIC.idx_bithon_exception_metrics_dimensions_INDEX_7 ON PUBLIC.bithon_exception_metrics(timestamp, appName, instanceName, uri, className) VALUES 438"; SQL statement:
insert into "bithon_exception_metrics" ("timestamp", "appName", "instanceName", "uri", "className", "exceptionCount") values (timestamp '2021-10-07 21:03:52.614', 'bithon-server-test', '10.169.24.104:9897', '', '', 3) [23505-200]
	at org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator.doTranslate(SQLErrorCodeSQLExceptionTranslator.java:247) ~[spring-jdbc-5.2.12.RELEASE.jar!/:5.2.12.RELEASE]
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:72) ~[spring-jdbc-5.2.12.RELEASE.jar!/:5.2.12.RELEASE]
	at org.springframework.boot.autoconfigure.jooq.JooqExceptionTranslator.translate(JooqExceptionTranslator.java:92) [spring-boot-autoconfigure-2.3.7.RELEASE.jar!/:2.3.7.RELEASE]
	at org.springframework.boot.autoconfigure.jooq.JooqExceptionTranslator.handle(JooqExceptionTranslator.java:81) [spring-boot-autoconfigure-2.3.7.RELEASE.jar!/:2.3.7.RELEASE]
	at org.springframework.boot.autoconfigure.jooq.JooqExceptionTranslator.exception(JooqExceptionTranslator.java:55) [spring-boot-autoconfigure-2.3.7.RELEASE.jar!/:2.3.7.RELEASE]
	at org.jooq.impl.ExecuteListeners.exception(ExecuteListeners.java:274) [jooq-3.13.6.jar!/:na]
	at org.jooq.impl.BatchMultiple.execute(BatchMultiple.java:133) [jooq-3.13.6.jar!/:na]
	at org.jooq.impl.BatchMultiple.execute(BatchMultiple.java:75) [jooq-3.13.6.jar!/:na]
	at com.sbss.bithon.server.metric.storage.jdbc.MetricJdbcWriter.write(MetricJdbcWriter.java:109) [bithon-server-collector-1.0-SNAPSHOT.jar!/:na]
	at com.sbss.bithon.server.metric.handler.AbstractMetricMessageHandler.process(AbstractMetricMessageHandler.java:120) [bithon-server-collector-1.0-SNAPSHOT.jar!/:na]
	at com.sbss.bithon.server.collector.sink.local.LocalMetricSink.lambda$process$1(LocalMetricSink.java:80) [bithon-server-collector-1.0-SNAPSHOT.jar!/:na]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_252]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_252]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_252]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_252]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_252]
Caused by: org.h2.jdbc.JdbcSQLIntegrityConstraintViolationException: Unique index or primary key violation: "PUBLIC.idx_bithon_exception_metrics_dimensions_INDEX_7 ON PUBLIC.bithon_exception_metrics(timestamp, appName, instanceName, uri, className) VALUES 438"; SQL statement:
insert into "bithon_exception_metrics" ("timestamp", "appName", "instanceName", "uri", "className", "exceptionCount") values (timestamp '2021-10-07 21:03:52.614', 'bithon-server-test', '10.169.24.104:9897', '', '', 3) [23505-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:459) ~[h2-1.4.200.jar!/:na]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429) ~[h2-1.4.200.jar!/:na]
	at org.h2.message.DbException.get(DbException.java:205) ~[h2-1.4.200.jar!/:na]
	at org.h2.message.DbException.get(DbException.java:181) ~[h2-1.4.200.jar!/:na]
	at org.h2.index.BaseIndex.getDuplicateKeyException(BaseIndex.java:103) ~[h2-1.4.200.jar!/:na]
	at org.h2.mvstore.db.MVSecondaryIndex.checkUnique(MVSecondaryIndex.java:221) ~[h2-1.4.200.jar!/:na]
	at org.h2.mvstore.db.MVSecondaryIndex.add(MVSecondaryIndex.java:196) ~[h2-1.4.200.jar!/:na]
	at org.h2.mvstore.db.MVTable.addRow(MVTable.java:531) ~[h2-1.4.200.jar!/:na]
	at org.h2.command.dml.Insert.insertRows(Insert.java:195) ~[h2-1.4.200.jar!/:na]
	at org.h2.command.dml.Insert.update(Insert.java:151) ~[h2-1.4.200.jar!/:na]
	at org.h2.command.CommandContainer.update(CommandContainer.java:198) ~[h2-1.4.200.jar!/:na]
	at org.h2.command.Command.executeUpdate(Command.java:251) ~[h2-1.4.200.jar!/:na]
	at org.h2.jdbc.JdbcStatement.executeUpdateInternal(JdbcStatement.java:168) ~[h2-1.4.200.jar!/:na]
	at org.h2.jdbc.JdbcStatement.executeBatch(JdbcStatement.java:768) ~[h2-1.4.200.jar!/:na]
	at com.alibaba.druid.pool.DruidPooledStatement.executeBatch$original$ziXhcPz0(DruidPooledStatement.java:791) ~[druid-1.1.16.jar!/:1.1.16]
	at com.alibaba.druid.pool.DruidPooledStatement.executeBatch$original$ziXhcPz0$accessor$oRtdqF75(DruidPooledStatement.java) ~[druid-1.1.16.jar!/:1.1.16]
	at com.alibaba.druid.pool.DruidPooledStatement$auxiliary$IYobBLlq.invoke(Unknown Source) ~[druid-1.1.16.jar!/:1.1.16]
	at com.sbss.bithon.agent.bootstrap.aop.AroundMethodAopImpl.intercept(AroundMethodAopImpl.java:64) ~[na:na]
	at com.sbss.bithon.agent.bootstrap.aop.MethodAop.intercept(MethodAop.java:47) ~[na:na]
	at com.alibaba.druid.pool.DruidPooledStatement.executeBatch(DruidPooledStatement.java) ~[druid-1.1.16.jar!/:1.1.16]
	at org.jooq.tools.jdbc.DefaultStatement.executeBatch(DefaultStatement.java:112) ~[jooq-3.13.6.jar!/:na]
	at org.jooq.tools.jdbc.DefaultStatement.executeBatch(DefaultStatement.java:112) ~[jooq-3.13.6.jar!/:na]
	at org.jooq.impl.BatchMultiple.execute(BatchMultiple.java:113) [jooq-3.13.6.jar!/:na]
```

**Comment by FrankChen021** [comment]
Turns out this is thrown from `org.springframework.boot.autoconfigure.jooq.JooqExceptionTranslator`, a class provided by spring.  And it's configured in `JooqAutoConfiguration`, and no way to replace it.

```java
	@Bean
	@Order(0)
	public DefaultExecuteListenerProvider jooqExceptionTranslatorExecuteListenerProvider() {
		return new DefaultExecuteListenerProvider(new JooqExceptionTranslator());
	}
```
