### ISSUE TITLE
Several bugs

### ISSUE THREAD

**Issue by FrankChen021** [FrankChen021/bithon#250]
1. when running in docker and the network is type of host, instance ip can be either a docker container ip or host ip. Best to set to host ip.

2. trace map
    if a tx is ended at httpClient or something else, the map lacks of next destination.

3. UI application selection state is not kept

**Comment by FrankChen021** [comment]
4. boring stack trace. Should omit such exception
```bash
[nioEventLoopGroup-5-1:ServiceMessageChannelHandler] Exception occurred when processing message
java.io.IOException: Connection reset by peer
	at sun.nio.ch.FileDispatcherImpl.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
```

**Comment by FrankChen021** [comment]
5.  `.map` should be added to the default suffix filter

**Comment by FrankChen021** [comment]
6. Exception in agent

```text
2021-12-16 15:21:44.435 [Agent WARN] - [main:AopLogger] Error occurred during invoking AbstractEndpointStart.after()
java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:911)
	at java.util.ArrayList$Itr.next(ArrayList.java:861)
	at org.bithon.agent.core.context.AppInstance.setPort(AppInstance.java:67)
	at org.bithon.agent.plugin.tomcat.interceptor.AbstractEndpointStart.onMethodLeave(AbstractEndpointStart.java:38)
	at org.bithon.agent.bootstrap.aop.AroundMethodAopImpl.intercept(AroundMethodAopImpl.java:81)
	at org.bithon.agent.bootstrap.aop.MethodAop.intercept(MethodAop.java:47)
	at org.apache.tomcat.util.net.AbstractEndpoint.start(AbstractEndpoint.java)
	at org.apache.coyote.AbstractProtocol.start(AbstractProtocol.java:614)
	at org.apache.catalina.connector.Connector.startInternal(Connector.java:1072)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
	at org.apache.catalina.core.StandardService.addConnector(StandardService.java:239)
	at org.springframework.boot.web.embedded.tomcat.TomcatWebServer.addPreviouslyRemovedConnectors(TomcatWebServer.java:282)
	at org.springframework.boot.web.embedded.tomcat.TomcatWebServer.start(TomcatWebServer.java:213)
	at org.springframework.boot.web.servlet.context.WebServerStartStopLifecycle.start(WebServerStartStopLifecycle.java:43)
	at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:182)
	at org.springframework.context.support.DefaultLifecycleProcessor.access$200(DefaultLifecycleProcessor.java:53)
	at org.springframework.context.support.DefaultLifecycleProcessor$LifecycleGroup.start(DefaultLifecycleProcessor.java:360)
	at org.springframework.context.support.DefaultLifecycleProcessor.startBeans(DefaultLifecycleProcessor.java:158)
	at org.springframework.context.support.DefaultLifecycleProcessor.onRefresh(DefaultLifecycleProcessor.java:122)
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:895)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:554)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:143)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:755)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:747)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:402)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:312)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1247)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1236)
	at org.bithon.server.starter.StarterApplication.main(StarterApplication.java:31)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:107)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88)
```

**Comment by FrankChen021** [comment]
All resolved.
