### ISSUE TITLE
NPE from jetty interceptor

### ISSUE THREAD

**Issue by FrankChen021** [FrankChen021/bithon#521]
![image](https://user-images.githubusercontent.com/6525742/220827447-c4679e62-943d-42f7-ab02-842f634041eb.png)

Relevant code

![image](https://user-images.githubusercontent.com/6525742/220827545-7cf9975b-b9d8-4f73-a0e3-f6a38f44b753.png)

Since this exception is raised at the end of the interceptor, it does not affect the execution of hooking, only causes verbose logging.

**Comment by FrankChen021** [comment]
Another NPE observed

```text
MethodDecoratorAdvice:55 - Exception occurred when executing onExit of [HttpsClient$New] for [HttpsClient]: class java.lang.Boolean cannot be cast to class java.net.HttpURLConnection (java.lang.Boolean and java.net.HttpURLConnection are in module java.base of loader 'bootstrap')
```

Above exception also causes following exception
```text
MethodDecoratorAdvice:55 - Exception occurred when executing onExit of [HttpClient$ParseHTTP] for [HttpClient]: null
```

**Comment by FrankChen021** [comment]
Full stack trace
```text
java.lang.NullPointerException
	at org.bithon.agent.plugin.jetty.interceptor.HttpChannel$Handle.onMethodEnter(HttpChannel$Handle.java:106)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:348)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:277)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
	at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:338)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:315)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:173)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:386)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:883)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1034)
	at java.base/java.lang.Thread.run(Thread.java:829)
```
