### ISSUE TITLE
Sink trace discarded

### ISSUE THREAD

**Issue by FrankChen021** [FrankChen021/bithon#633]
![image](https://github.com/FrankChen021/bithon/assets/6525742/77ffb9b9-dbad-485b-bf44-6693558453ac)

**Comment by FrankChen021** [comment]
httpoutgoing
![image](https://github.com/FrankChen021/bithon/assets/6525742/09f3dd80-83ae-4c42-acfa-22438976a349)

**Comment by FrankChen021** [comment]
![image](https://github.com/FrankChen021/bithon/assets/6525742/e645aedc-e13f-4b64-a3c3-14b39b67fdde)

**Comment by FrankChen021** [comment]
Recorded same exceptions on 4 instances during 15:30-15:40. However, this exception was caught by `TransformSpec` in the metrics handling thread

```text
[bTxId: bd83866b247a438c9fbb48b561842efa, bSpanId: 242840421720c46c, bMode: L] Failed to transform input data

java.lang.IllegalArgumentException: URLDecoder: Illegal hex characters in escape (%) pattern - For input string: "A/"
	at java.net.URLDecoder.decode(URLDecoder.java:194) ~[na:1.8.0_342]
	at org.bithon.server.sink.common.service.UriNormalizer.normalize(UriNormalizer.java:84) ~[server-sink-1.1.1-RELEASE.jar!/:na]
	at org.bithon.server.sink.common.service.UriNormalizer.normalize(UriNormalizer.java:75) ~[server-sink-1.1.1-RELEASE.jar!/:na]
	at org.bithon.server.sink.metrics.transformer.UriNormalizationTransformer.transformInternal(UriNormalizationTransformer.java:46) ~[server-sink-1.1.1-RELEASE.jar!/:na]
	at org.bithon.server.storage.datasource.input.transformer.AbstractSimpleTransformer.transform(AbstractSimpleTransformer.java:40) ~[server-storage-1.1.1-RELEASE.jar!/:na]
	at org.bithon.server.storage.datasource.input.TransformSpec.transform(TransformSpec.java:93) ~[server-storage-1.1.1-RELEASE.jar!/:na]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:174) ~[na:1.8.0_342]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1384) ~[na:1.8.0_342]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482) ~[na:1.8.0_342]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472) ~[na:1.8.0_342]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) ~[na:1.8.0_342]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[na:1.8.0_342]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:566) ~[na:1.8.0_342]
	at org.bithon.server.sink.metrics.MetricMessageHandler$MetricSinkRunnable.run(MetricMessageHandler.java:130) ~[server-sink-1.1.1-RELEASE.jar!/:na]
	at org.bithon.agent.plugin.thread.utils.ObservedTask.runWithTracing(ObservedTask.java:71) ~[na:na]
	at org.bithon.agent.plugin.thread.utils.ObservedTask.run(ObservedTask.java:58) ~[na:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_342]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_342]
	at java.lang.Thread.run(Thread.java:750) ~[na:1.8.0_342]
```

**Comment by FrankChen021** [comment]
![image](https://github.com/FrankChen021/bithon/assets/6525742/441989d1-0a05-4d46-808f-cf451de825e7)
![image](https://github.com/FrankChen021/bithon/assets/6525742/9fb30101-8650-4b27-8887-6031087f51c0)
