### ISSUE TITLE
java.lang.NoClassDefFoundError from kafka plugin

### ISSUE THREAD

**Issue by FrankChen021** [FrankChen021/bithon#641]
```
java.lang.NoClassDefFoundError: org/apache/kafka/clients/ClientResponse
	at org.bithon.agent.plugin.apache.kafka.producer.interceptor.Sender$HandleProduceResponse.before(Sender$HandleProduceResponse.java:37) ~[?:?]
	at org.apache.kafka.clients.producer.internals.Sender.handleProduceResponse(Sender.java:549) ~[kafka-clients-2.8.0.jar:?]
	at org.apache.kafka.clients.producer.internals.Sender.lambda$sendProduceRequest$3(Sender.java:793) ~[kafka-clients-2.8.0.jar:?]
	at org.apache.kafka.clients.ClientResponse.onComplete(ClientResponse.java:109) [kafka-clients-2.8.0.jar:?]
	at org.apache.kafka.clients.NetworkClient.completeResponses(NetworkClient.java:584) [kafka-clients-2.8.0.jar:?]
	at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:576) [kafka-clients-2.8.0.jar:?]
	at org.apache.kafka.clients.producer.internals.Sender.runOnce(Sender.java:327) [kafka-clients-2.8.0.jar:?]
	at org.apache.kafka.clients.producer.internals.Sender.run(Sender.java:242) [kafka-clients-2.8.0.jar:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_275]
```

**Comment by FrankChen021** [comment]
```
java.lang.NoClassDefFoundError: org/apache/kafka/common/TopicPartition
	at org.bithon.agent.plugin.apache.kafka.producer.interceptor.SenderMetrics$UpdateProduceRequestMetrics.after(SenderMetrics$UpdateProduceRequestMetrics.java:84) ~[?:?]
	at org.apache.kafka.clients.producer.internals.Sender$SenderMetrics.updateProduceRequestMetrics(Sender.java:944) [kafka-clients-2.8.0.jar:?]
	at org.apache.kafka.clients.producer.internals.Sender.sendProducerData(Sender.java:389) [kafka-clients-2.8.0.jar:?]
	at org.apache.kafka.clients.producer.internals.Sender.runOnce(Sender.java:326) [kafka-clients-2.8.0.jar:?]
	at org.apache.kafka.clients.producer.internals.Sender.run(Sender.java:242) [kafka-clients-2.8.0.jar:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_275]
```

**Comment by FrankChen021** [comment]
ocurred when kafka-emitter in druid is enabled

**Comment by FrankChen021** [comment]
The loader that works in other projects:
<img width="659" alt="image" src="https://github.com/FrankChen021/bithon/assets/6525742/fc3ae375-4de0-4fac-a409-06e22d55c30e">

The loader that does not work in above case:
<img width="770" alt="image" src="https://github.com/FrankChen021/bithon/assets/6525742/3fb99a0a-5e40-4dc7-8361-d00d16bc8c59">
<img width="666" alt="image" src="https://github.com/FrankChen021/bithon/assets/6525742/6b2b3fbc-2a54-4b22-bd27-c75a4df55f9f">
<img width="1158" alt="image" src="https://github.com/FrankChen021/bithon/assets/6525742/ab9a97d2-1fb6-47a4-99e2-0c6b3cbaa1fe">

**Comment by FrankChen021** [comment]
<img width="1192" alt="image" src="https://github.com/user-attachments/assets/b2201994-1868-4c60-9d54-7e7458af2c6e">
This diagram explains why it works in some other cases and why not this exception is raised in such scenario

**Comment by FrankChen021** [comment]
and how this problem is fixed
<img width="715" alt="image" src="https://github.com/user-attachments/assets/767d820f-6273-4534-842e-c2f61cdc3bb1">
