### ISSUE TITLE
Failed to transform for particular class 

### ISSUE THREAD

**Issue by FrankChen021** [FrankChen021/bithon#703]
```
[bTxId: , bSpanId: , bMode: ] Failed to transform org.bithon.server.kafka.KafkaConsumerEventListener

java.lang.reflect.MalformedParametersException: Invalid parameter name ""
	at java.lang.reflect.Executable.verifyParameters(Executable.java:386) ~[na:1.8.0_342]
	at java.lang.reflect.Executable.privateGetParameters(Executable.java:416) ~[na:1.8.0_342]
	at java.lang.reflect.Executable.getParameters(Executable.java:357) ~[na:1.8.0_342]
	at sun.reflect.GeneratedMethodAccessor7.invoke(Unknown Source) ~[na:na]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_342]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_342]
	at org.bithon.shaded.net.bytebuddy.utility.Invoker$Dispatcher.invoke(Unknown Source) [na:na]
	at org.bithon.shaded.net.bytebuddy.utility.dispatcher.JavaDispatcher$Dispatcher$ForNonStaticMethod.invoke(JavaDispatcher.java:1032) [na:na]
	at org.bithon.shaded.net.bytebuddy.utility.dispatcher.JavaDispatcher$ProxiedInvocationHandler.invoke(JavaDispatcher.java:1162) [na:na]
	at org.bithon.shaded.net.bytebuddy.description.method.$Proxy9.getParameters(Unknown Source) ~[na:na]
	at org.bithon.shaded.net.bytebuddy.description.method.ParameterDescription$ForLoadedParameter.isNamed(ParameterDescription.java:295) ~[na:na]
	at org.bithon.shaded.net.bytebuddy.description.method.ParameterDescription$AbstractBase.asToken(ParameterDescription.java:187) ~[na:na]
	at org.bithon.shaded.net.bytebuddy.description.method.ParameterDescription$AbstractBase.asToken(ParameterDescription.java:135) ~[na:na]
	at org.bithon.shaded.net.bytebuddy.description.method.ParameterList$AbstractBase.asTokenList(ParameterList.java:96) ~[na:na]
	at org.bithon.shaded.net.bytebuddy.description.method.MethodDescription$AbstractBase.asToken(MethodDescription.java:890) ~[na:na]
	at org.bithon.shaded.net.bytebuddy.description.method.MethodDescription$AbstractBase.asToken(MethodDescription.java:445) ~[na:na]
	at org.bithon.shaded.net.bytebuddy.description.method.MethodList$AbstractBase.asTokenList(MethodList.java:90) ~[na:na]
	at org.bithon.shaded.net.bytebuddy.dynamic.scaffold.InstrumentedType$Factory$Default$1.represent(InstrumentedType.java:438) ~[na:na]
	at org.bithon.shaded.net.bytebuddy.ByteBuddy.redefine(ByteBuddy.java:886) ~[na:na]
	at org.bithon.shaded.net.bytebuddy.agent.builder.AgentBuilder$TypeStrategy$Default$2.builder(AgentBuilder.java:2639) ~[na:na]
	at org.bithon.shaded.net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.doTransform(AgentBuilder.java:12095) [na:na]
	at org.bithon.shaded.net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.transform(AgentBuilder.java:12041) [na:na]
	at org.bithon.shaded.net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.access$1800(AgentBuilder.java:11758) [na:na]
	at org.bithon.shaded.net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer$LegacyVmDispatcher.run(AgentBuilder.java:12441) [na:na]
	at org.bithon.shaded.net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer$LegacyVmDispatcher.run(AgentBuilder.java:12381) [na:na]
	at java.security.AccessController.doPrivileged(Native Method) [na:1.8.0_342]
	at org.bithon.shaded.net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.doPrivileged(AgentBuilder.java) [na:na]
	at org.bithon.shaded.net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.transform(AgentBuilder.java:11950) [na:na]
	at sun.instrument.TransformerManager.transform(TransformerManager.java:188) [na:1.8.0_342]
	at sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:428) [na:1.8.0_342]
	at sun.instrument.InstrumentationImpl.retransformClasses0(Native Method) [na:1.8.0_342]
	at sun.instrument.InstrumentationImpl.retransformClasses(InstrumentationImpl.java:144) [na:1.8.0_342]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_342]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_342]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_342]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_342]
	at org.bithon.shaded.net.bytebuddy.utility.Invoker$Dispatcher.invoke(Unknown Source) [na:na]
	at org.bithon.shaded.net.bytebuddy.utility.dispatcher.JavaDispatcher$Dispatcher$ForNonStaticMethod.invoke(JavaDispatcher.java:1032) [na:na]
	at org.bithon.shaded.net.bytebuddy.utility.dispatcher.JavaDispatcher$ProxiedInvocationHandler.invoke(JavaDispatcher.java:1162) [na:na]
	at org.bithon.shaded.net.bytebuddy.agent.builder.$Proxy22.retransformClasses(Unknown Source) [na:na]
	at org.bithon.shaded.net.bytebuddy.agent.builder.AgentBuilder$RedefinitionStrategy$Collector$ForRetransformation.doApply(AgentBuilder.java:8177) [na:na]
	at org.bithon.shaded.net.bytebuddy.agent.builder.AgentBuilder$RedefinitionStrategy$Collector.apply(AgentBuilder.java:7992) [na:na]
	at org.bithon.shaded.net.bytebuddy.agent.builder.AgentBuilder$RedefinitionStrategy.apply(AgentBuilder.java:5689) [na:na]
	at org.bithon.shaded.net.bytebuddy.agent.builder.AgentBuilder$Default.doInstall(AgentBuilder.java:11126) [na:na]
	at org.bithon.shaded.net.bytebuddy.agent.builder.AgentBuilder$Default.installOn(AgentBuilder.java:11044) [na:na]
	at org.bithon.agent.instrumentation.aop.interceptor.installer.DynamicInterceptorInstaller.install(DynamicInterceptorInstaller.java:106) [na:na]
	at org.bithon.agent.observability.aop.BeanMethodAopInstaller.lambda$static$0(BeanMethodAopInstaller.java:50) [na:na]
	at org.bithon.agent.observability.context.AppInstance.setPort(AppInstance.java:84) ~[na:na]
	at org.bithon.agent.plugin.tomcat.interceptor.AbstractEndpoint$Start.after(AbstractEndpoint$Start.java:52) ~[na:na]
	at org.apache.tomcat.util.net.AbstractEndpoint.start(AbstractEndpoint.java:1294) ~[tomcat-embed-core-9.0.46.jar!/:n
```

**Comment by FrankChen021** [comment]
Related to the distribution.
