### ISSUE TITLE
NPE during transformation

### ISSUE THREAD

**Issue by FrankChen021** [FrankChen021/bithon#759]
```
java.lang.NullPointerException: Cannot invoke "String.substring(int)" because the return value of "java.net.URI.getPath()" is null
	at org.bithon.server.commons.utils.DbUtils.parseConnectionString(DbUtils.java:69) ~[server-commons-1.1.1-RELEASE.jar!/:na]
	at org.bithon.server.pipeline.metrics.transform.ConnectionStringTransformer.transform(ConnectionStringTransformer.java:45) ~[server-pipeline-1.1.1-RELEASE.jar!/:na]
	at org.bithon.server.pipeline.common.transform.TransformSpec.transform(TransformSpec.java:96) ~[server-pipeline-1.1.1-RELEASE.jar!/:na]
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:178) ~[na:na]
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[na:na]
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[na:na]
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682) ~[na:na]
	at org.bithon.server.pipeline.metrics.exporter.MetricMessageHandler$MetricSinkRunnable.run(MetricMessageHandler.java:131) ~[server-pipeline-1.1.1-RELEASE.jar!/:na]
	at org.bithon.agent.plugin.jdk.thread.utils.ObservedTask.runWithTracing(ObservedTask.java:72) ~[na:na]
	at org.bithon.agent.plugin.jdk.thread.utils.ObservedTask.run(ObservedTask.java:59) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:840) ~[na:na]
```

**Comment by FrankChen021** [comment]
jdbc:mysql:loadbalance://**internally_generated**1711720265336**
