### ISSUE TITLE
ClassCastException in Kafka network interceptor

### ISSUE THREAD

**Issue by FrankChen021** [FrankChen021/bithon#880]
Kafka client 3.6, the exception happens once

```java
java.lang.reflect.InvocationTargetException:null
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at org.bithon.agent.instrumentation.aop.interceptor.InterceptorSupplier.createInterceptor(InterceptorSupplier.java:91)
	at org.bithon.agent.instrumentation.aop.interceptor.InterceptorSupplier.get(InterceptorSupplier.java:75)
	at org.bithon.agent.instrumentation.aop.interceptor.InterceptorSupplier.get(InterceptorSupplier.java:32)
	at org.bithon.agent.instrumentation.aop.interceptor.InterceptorManager.getInterceptor(InterceptorManager.java:63)
	at org.apache.kafka.clients.NetworkClient.completeResponses(NetworkClient.java:588)
	at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:575)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:280)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:251)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:242)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.awaitMetadataUpdate(ConsumerNetworkClient.java:164)
	at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.poll(ConsumerCoordinator.java:573)
	at org.apache.kafka.clients.consumer.KafkaConsumer.updateAssignmentMetadataIfNeeded(KafkaConsumer.java:1272)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1236)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1216)
        ...
Caused by: java.lang.ClassCastException: class org.bithon.agent.plugin.apache.kafka.network.metrics.NetworkMetricRegistry cannot be cast to class org.bithon.agent.plugin.apache.kafka.network.metrics.NetworkMetricRegistry (org.bithon.agent.plugin.apache.kafka.network.metrics.NetworkMetricRegistry is in unnamed module of loader org.bithon.agent.instrumentation.loader.PluginClassLoader @3b82b8e; org.bithon.agent.plugin.apache.kafka.network.metrics.NetworkMetricRegistry is in unnamed module of loader org.bithon.agent.instrumentation.loader.PluginClassLoader @20ccaa72)
	at org.bithon.agent.plugin.apache.kafka.network.interceptor.NetworkClient$CompleteResponses.<init>(NetworkClient$CompleteResponses.java:44)
	... 30 more
java.lang.ClassCastException:class org.bithon.agent.plugin.apache.kafka.network.metrics.NetworkMetricRegistry cannot be cast to class org.bithon.agent.plugin.apache.kafka.network.metrics.NetworkMetricRegistry (org.bithon.agent.plugin.apache.kafka.network.metrics.NetworkMetricRegistry is in unnamed module of loader org.bithon.agent.instrumentation.loader.PluginClassLoader @3b82b8e; org.bithon.agent.plugin.apache.kafka.network.metrics.NetworkMetricRegistry is in unnamed module of loader org.bithon.agent.instrumentation.loader.PluginClassLoader @20ccaa72)
java.lang.ClassCastException: class org.bithon.agent.plugin.apache.kafka.network.metrics.NetworkMetricRegistry cannot be cast to class org.bithon.agent.plugin.apache.kafka.network.metrics.NetworkMetricRegistry (org.bithon.agent.plugin.apache.kafka.network.metrics.NetworkMetricRegistry is in unnamed module of loader org.bithon.agent.instrumentation.loader.PluginClassLoader @3b82b8e; org.bithon.agent.plugin.apache.kafka.network.metrics.NetworkMetricRegistry is in unnamed module of loader org.bithon.agent.instrumentation.loader.PluginClassLoader @20ccaa72)
	at org.bithon.agent.plugin.apache.kafka.network.interceptor.NetworkClient$CompleteResponses.<init>(NetworkClient$CompleteResponses.java:44)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at org.bithon.agent.instrumentation.aop.interceptor.InterceptorSupplier.createInterceptor(InterceptorSupplier.java:91)
	at org.bithon.agent.instrumentation.aop.interceptor.InterceptorSupplier.get(InterceptorSupplier.java:75)
	at org.bithon.agent.instrumentation.aop.interceptor.InterceptorSupplier.get(InterceptorSupplier.java:32)
	at org.bithon.agent.instrumentation.aop.interceptor.InterceptorManager.getInterceptor(InterceptorManager.java:63)
	at org.apache.kafka.clients.NetworkClient.completeResponses(NetworkClient.java:588)
	at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:575)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:280)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:251)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:242)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.awaitMetadataUpdate(ConsumerNetworkClient.java:164)
	at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.poll(ConsumerCoordinator.java:573)
	at org.apache.kafka.clients.consumer.KafkaConsumer.updateAssignmentMetadataIfNeeded(KafkaConsumer.java:1272)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1236)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1216)
	...

```

**Comment by FrankChen021** [comment]
related to #641

**Comment by FrankChen021** [comment]
#645 Fixed this problem by this hierachy

<img width="715" alt="image" src="https://github.com/user-attachments/assets/0568d14c-358b-4973-b868-e6626e8a05e7">

The problem is that one Interceptor might be loaded in different InterceptorClassLoaders, and inside the interceptor, they might access some singleton classes. The singleton instance is instantiate in one class loader, it can NOT be used in another class loader

**Comment by FrankChen021** [comment]
`NetworkMetricRegistry` is changed to be allowed multiple instances as a workaround.
